#!/usr/bin/bash
# Simply executes Shodan CLI queries
# so output can be easily bg/tailed
# 2024/gad

# If no args (programmer error)
if [ -z "$1" ] || [ ! -r "$1" ]; then
  head -5 $0 | tail -4
  echo -e "$0 <file_with_recon_parameters>\n"
  exit
fi

# Init Shodan
./uh-shodan-init

# NO
# for line in $(cat "$1"); do 
#  echo "$0 : ./uh-recon-shodan-query \"$line"""
# done

cat "$1" | while IFS= read -r x; do
  echo "./uh-recon-shodan-query $x"
  echo ./uh-recon-shodan-query $x | sh
done
